name: Scheduled Component File Update

on:
  schedule:
    - cron: '1 2 * * *' # daily at 2:01 AM UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  maintenance_updates:
    runs-on: ubuntu-latest

    env:
      EQ_API_KEY: ${{ secrets.EQ_API_KEY }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out default branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
          ref: develop

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Install rExpertQuery package
        run: |
          install.packages("remotes")
          remotes::install_github(
            "USEPA/rExpertQuery",
            ref = "develop",
            dependencies = TRUE,
            force = TRUE
          )
        shell: Rscript {0}

      - name: Update ATTAINS domain values and save CSV
        run: |
          library(rExpertQuery)

          # Get/update the data
          df <- rExpertQuery:::EQ_UpdateInternalDomainValues(
            api_key = rExpertQuery:::.setEQKey()
          )

          # Ensure output directory exists
          dir.create("inst/extdata", recursive = TRUE, showWarnings = FALSE)

          # Save as CSV
          write.csv(df, "inst/extdata/EQParamsCrosswalk.csv", row.names = FALSE)
        shell: Rscript {0}

      - name: Commit and push updates
        run: |
           set -e
           git config user.name "github-actions[bot]"
           git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
           BRANCH="develop"
           git add inst/extdata/EQParamsCrosswalk.csv
           if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
           fi
           git commit -m "chore: update EQParamsCrosswalk"
           git push origin "HEAD:$BRANCH"
